name: Sanity check
on:
  push:
    tags:
      - v*
    branches:
      - '*'
      - main
  pull_request:
permissions:
  contents: read
jobs:
  sanity:
    name: Sanity check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18.0
          stable: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.46.2

      - name: Run tests
        run: make test

